# Generated by Django 4.2.1 on 2023-05-31 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_settinguser_email_alter_settinguser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settinguser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setting_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Userr',
        ),
    ]
